### ISSUE TITLE
video_mode list hangs

### ISSUE THREAD

**Issue by CarlFK** [timvideos/HDMI2USB#134]
x c p 0
see uptime incrementing 
video_mode list
see uptime stop incrementing 
console hangs

**Comment by mithro** [comment]
Does this happen in both the Atlys & Opsis?

Which versions have you tested that have this issue?

**Comment by CarlFK** [comment]
Both Atlys and Opsis, 
I have only confirmed it on current unstable:

H2U 00:03:58>version 

hardware version info
===============================================
           DNA: 013b226b831ac479
           MAC: d8:80:39:57:02:78

gateware version info
===============================================
      platform: opsis
        target: HDMI2USB
      revision: f9c031da3ea127613bd0dfd0c524687762c6a882

firmware version info
===============================================
      platform: opsis
        target: hdmi2usb
    git commit: f9c031da3ea127613bd0dfd0c524687762c6a882
    git branch: master
  git describe: v0.0.3-730-gf9c031d-dirty
    git status:
    --
     M ../../../../third_party/litepcie
     M ../../../../third_party/litesata
     M ../../../../third_party/liteusb
    --

         built: Jul 22 2017 14:57:34
        uptime: 00:04:10
-----------------------------------------------
H2U 00:04:10>video_mode list
(hang)

**Comment by mithro** [comment]
It would be really useful to find out at what point this broke.

Any chance you could try and find the latest version where this doesn't
lock up?

Do you know how to do a bisect?

On 26 Jul. 2017 9:16 am, "Carl Karsten" <notifications@github.com> wrote:

Both Atlys and Opsis,
I have only confirmed it on current unstable:

H2U 00:03:58>version
hardware version info

       DNA: 013b226b831ac479
       MAC: d8:80:39:57:02:78

gateware version info

  platform: opsis
    target: HDMI2USB
  revision: f9c031da3ea127613bd0dfd0c524687762c6a882

firmware version info

  platform: opsis
    target: hdmi2usb
git commit: f9c031da3ea127613bd0dfd0c524687762c6a882
git branch: master

git describe: v0.0.3-730-gf9c031d-dirty
git status:
--
M ../../../../third_party/litepcie
M ../../../../third_party/litesata
M ../../../../third_party/liteusb
--

     built: Jul 22 2017 14:57:34
    uptime: 00:04:10

------------------------------

H2U 00:04:10>video_mode list
(hang)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/timvideos/HDMI2USB/issues/134#issuecomment-317900558>,
or mute the thread

**Comment by CarlFK** [comment]
On the Opsis and Atlys, hitting reset brings it back to life

**Comment by CarlFK** [comment]
l crashes Atlys 
 v0.0.3-698-g7b7714d-dirty        
  built: Apr  2 2017 07:31:09 -

**Comment by CarlFK** [comment]
H2U 00:00:10>version 

hardware version info
===============================================
           DNA: 013b226b831ac479
           MAC: d8:80:39:57:02:78

gateware version info                                            
===============================================                  
      platform: opsis                                            
        target: HDMI2USB                                         
      revision: 2f815c12abf17756c4d8d22bf9f057d1b6e49aa1         

firmware version info
===============================================
      platform: opsis
        target: hdmi2usb
    git commit: 2f815c12abf17756c4d8d22bf9f057d1b6e49aa1
    git branch: master
  git describe: v0.0.3-696-g2f815c1-dirty
    git status:
    --
     M ../../../../third_party/litepcie
     M ../../../../third_party/litesata
     M ../../../../third_party/liteusb
    --

         built: Mar 31 2017 04:57:26
        uptime: 00:00:13
-----------------------------------------------
H2U 00:00:13>x c p 0
Connecting pattern to output0
H2U 00:00:48>m l

crash

(08:37:13 PM) mithro: CarlFK: So it looks like it has always crashed with flash.bin stuff...

**Comment by mithro** [comment]
This issue was moved to timvideos/HDMI2USB-litex-firmware#331
